# Generated by Django 5.1 on 2024-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaApp', '0002_remove_post_image_delete_image_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/profile_pictures'),
        ),
    ]
