# Generated by Django 5.1 on 2024-09-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaApp', '0003_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/message_photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/profile_pictures'),
        ),
    ]
